name: Wool & Wood Tests and Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testsuite:
    runs-on: ubuntu-18.04

    steps:
      - name: Enable MySQL
        run: sudo systemctl start mysql.service

      - name: Create databases and test user in MySQL
        run: |
         mysql -u root -proot -e "CREATE DATABASE wool_and_wood CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
         mysql -u root -proot -e "CREATE DATABASE test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
         mysql -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'test'@'%' identified by 'test"

      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - name: Validate Composer Files
        run: composer validate

      - name: Cache Composer Packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.PACKAGES_ACCESS_TOKEN }}" }}'
        run: composer install --no-interaction --no-plugins

      - name: Run Migrations
        run: |
          php bin/cake.php migrations migrate
          php bin/cake.php migrations seed --seed DatabaseSeed
      - name: Run Code Sniffer
        if: ${{ always() }}
        run: composer cs-check

      - name: Run Annotations
        if: ${{ success() }}
        run: php bin/cake.php annotate all -v -d --ci

      - name: Run PHPStan
        if: ${{ always() }}
        run: composer stan

      - name: Run Unit Tests
        if: ${{ success() }}
        run: composer test


